version: '3.8'
services:
  db:
    image: mariadb:10.9.1-rc-jammy
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - logixboard
    env_file:
      - "db-secrets.env"
      - "db-config.env"

volumes:
  db-data:
  
networks:
  logixboard:
    
    